version: '3.8'

services:
  postgres-enviroment:
    image: postgres:latest
    container_name: postgres-enviroment-db
    environment:
      POSTGRES_DB: enviroment_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5440:5432"
    volumes:
      - postgres-enviroment-data:/var/lib/postgresql
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d enviroment_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ms-enviroment:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: ms-enviroment
  #   env_file:
  #     - .env
  #   ports:
  #     - "8087:8087"
  #   depends_on:
  #     postgres-enviroment:
  #       condition: service_healthy
  #   networks:
  #     - microservices-network
  #   restart: unless-stopped

volumes:
  postgres-enviroment-data:

networks:
  microservices-network:
    driver: bridge
